project:
  type: book
  output-dir: docs

book:
  title: "A Project-based Approach to Introductory R and Python for Data Science"
  author: 
    - name: "David J. Stokes"
      email: "djstokes@ncsu.edu"
    - name: "Mahmoud Harding"
      email: "mhardin2@ncsu.edu"
  date: ""
  license: "CC BY-NC-SA"
  chapters:
    - index.qmd
    - proj1R.qmd
    - proj2R.qmd
    - proj3R.qmd
    - proj4P.qmd
    - proj5P.qmd
    - proj6P.qmd
    - proj7R.qmd
    - proj8.qmd
    - references.qmd

  appendices:
    - appendix-a.qmd

bibliography: references.bib
csl: frontiers-in-applied-mathematics-and-statistics.csl

format:
  html:
    theme: cosmo
    link-external-newwindow: true
    #css: 
    #include-before-body: 
    include-after-body: "license-footer.html"

  pdf:
    documentclass: scrreprt
    code-overflow: wrap
    include-in-header: |
      \usepackage{afterpage}
      \newcommand{\copyrightpage}{%
        \thispagestyle{empty}
        \vspace*{\fill}
        \begin{center}
        \textbf{\Large Copyright Notice}\\[2em]
        Copyright \textcopyright\ 2025 First Author Name and Second Author Name\\[1em]
        This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.\\[1em]
        \url{http://creativecommons.org/licenses/by-nc-sa/4.0/}\\[2em]
        For more information about this license, visit:\\
        \url{https://creativecommons.org/licenses/by-nc-sa/4.0/}
        \end{center}
        \vspace*{\fill}
        \newpage
      }

jupyter: python3 

editor: source

