# Project Part 5: Communicating results

In the previous chapters we've gone from explaining our data and the associated metadata - via our data dictionaries - to diving into our data utilizing data moves. These pre-processing workflow steps served as a means towards grounding our investigations of interest, subsequently supported by the powerful tools of data visualization. Now, we are tasked with a culminating step in our workflow - communicating results. 

To accomplish this final milestone, let's consider a few guidelines, criteria, and programming features that we can leverage to help with bringing the components of our workflow together as a presentation.

## Presentation Guidelines

The bullet points below are the guidelines for your presentation. These considerations can be used beyond this project, more generally, as big picture concepts and explanatory needs for building and communicating a data investigation. 

 - Describe your data 
 
The data description should include important contextual and background information. This is essentially a summary of your data dictionary.

 - Explain what interests you about the dataset & why you chose it.
 
Although many data investigations aren't necessarily interest driven, making data connections through interest and relevance can be a powerful tool to boost, motivate and/or facilitate understanding. In some cases, identifying interests in the data or using interests to drive a data investigation can allow you to access your prior knowledge and experience. Or, perhaps you chose the data because you were interested in investigating something new.

  - Explain your data investigation or research question of interest?

During this step, you should describe any hypotheses you generated or expectations that you may have had going into the investigations. Relatedly, you should describe your dataset characteristics in terms of your data investigation. This step might be different from your previous data descriptions in that you might desrcibe a subset of your data in terms of the hypotheses and questions you seek to investigate. Here, you might include more information about the meaning and measures of certain variables. Additionally, you may have visualizations or tables that help you describe aspects of the data relevant to your investigation.

 - Explain how you processed your data (e.g, tell us about your data moves).
 
For this step you can elaborate on the *why* behind your data filtering or subsetting choices (among other data processing choices). You might explain why you used averages, or why you created a new variable (e.g., created levels from a continuous variable, merged your supplemental data by a common ID, etc.).

 - Explain what you did to investigate your question of interest.

For this step, describe what your analysis was and why you chose such a method. It's possible that your analysis step required additional data moves. For example, if you decided to visualize a trend in the data, perhaps you had to reformat information (as seen in previous chapters) in order to create your desired data representation.

 - Explain what you found.

In communicating your findings, you should provide a contextual explanation. Or, if your data investigation and the related analysis methods were exploratory, you might describe the insight you found that require further investigation, perhaps including suggestions for additional needs and lines of inquiry. These might include recommendations for additional measures and sources that would allow for answering the related questions. 

The need for extra information is also related to the limitations of your data. There may be limitations to the generalizability of your findings and the conclusions that can be garnered. For example, a visual trend might be a strong suggestion for a particular relationship, but the strength of the relationship and related statements you might want to make could be further supported by formal statistical modeling, analysis, and related diagnostics.  

 - Describe how this project relates to (or informs, or does not relate to or inform) your idea of data science & programming.

For this project, you should reflect on your process and connect it to data science and project workflows. You might look back at chapter one to see how your process aligned or differed from the frameworks presented there. Consider and explain where you might use AI in a particular project or workflow phase that you may not have already. Consider what you might do differently in a new individual project, or in a project team setting. Perhaps you have ideas for your personal data science workflow philosophy!   
 
## What else?

The format in which you choose to present your information is important. Many of the components above can be reported directly from default programming output. However, you should not just present the default output from something like the `summary()` function in R, for example. This information is undoubtedly useful, but you should reformat this type of output to include what's relevant and important with the same considerations you might have for a data visualization (e.g., minimizing clutter, adding contrast between rows of information, etc.).

Likewise, you should not include all of your code in your presentation. For example, there would not be a need to show your coding process for creating a particular data visualization. In fact, you might choose to hide all of your code within your presentation. You would have your (well commented) code accessible apart from your presentation as part of the reproducibility process and, in this case, as a course requirement.

## A few resources

 - If you choose to create your presentation within `quarto`, check out this resource: [Quarto Presentations](https://quarto.org/docs/presentations/).
 
 - To create formatted tables, consider the [kableExtra package](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html)
 
## Finally

Congratulations on learning to use R and Python within a data science workflow. You're now ready for your next step in your data science and AI learning journey!

